config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title,:content,:image, presence: true
  mount_uploader :image, ImageUploader
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name:"User"
  belongs_to :followed, class_name:"User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :active_relationships, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
  has_many :passive_relationships, class_name:"Relationship", foreign_key:"followed_id", dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  mount_uploader :avatar, ImageUploader

  validates :nickname,  length: { maximum: 15 }, uniqueness: true, presence: true
  validates :email,  length: { maximum: 30 }, uniqueness: true
  validates :avatar, presence: true


  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_in_path_for(resource)
  #   root_path # ログイン後に遷移するpathを設定
  # end





  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:nickname,:avatar])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update 
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to root_path
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content,:image).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to root_path
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit 
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_followers'
  end

  private 

  def user_params 
    params.require(:user).permit(:nickname,:email,:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_notifications.html.erb
<div class="notification">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
  <% end %>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Favoritepost</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Bilbo|Dancing+Script|Gloria+Hallelujah|Permanent+Marker|Yellowtail&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/notifications' %>
    <div class = "header">
      <div class = "header__left">
        <h1><%= link_to 'Favorite Post', root_path ,class:"app-title" %></h1>
      </div>
      <div class = "header__right">
        <% if user_signed_in? %>
          <%= link_to current_user.nickname, "/users/#{current_user.id}",class:"login-user" %>
          <%= link_to "投稿", new_post_path, class: "post-btn" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout-btn" %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "login-btn" %>
          <%= link_to "新規登録", new_user_registration_path, class: "registration-btn" %>
        <% end %>
      </div>
    </div>

      <%= yield %>

  </body>
</html>

app/views/posts/edit.html.erb
<div class="contents row">
  <div class="main">
    <%= form_with model: @post do |form| %>
      <h3>
        投稿内容
      </h3>
      <div class = "form-field">
        <%= form.label :title, "タイトル" %><br />
        <%= form.text_field :title,class:"form-control",autocomplete:"title" %>
      </div>
      <div class="form-group">
        <%= form.label :image, "画像" %><br />
        <%= form.file_field :image, autofocus: true, autocomplete: "avatar",class:"file-filed" %>
      </div>
      <div class = "form-field">
        <%= form.label :content, "本文" %><br />
        <%= form.text_area :content,class:"form-control",autocomplete:"content" %>
      </div>
        <%= form.submit "編集する", class:"post-new-btn" %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <% @posts.each do |post| %>
    <div class = "col-md-4 main-content">
      <%= link_to  "/users/#{post.user_id}", class:"main-content__link" do %>
        <div class = "index-avatar">
          <div class = "index-avatar__div">
            <%= image_tag post.user.avatar_url, class:"index-avatar__div__image" %>
            <span class = "index-nickname"><%= post.user.nickname %></span>
          </div>
        </div>
      <% end %>

      <%= link_to  "/posts/#{post.id}", class:"contributor" do %>
        <div class = "index-right">
          <div class = "post-title">
            <%= post.title %>
          </div>
          <p class = "post-time"><%= post.created_at.to_s(:datetime_jp) %></p>
        </div>
        <div class="content-image">
          <%= image_tag post.image_url,class:"index-image" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="contents row">
  <div class="main">
    <%= form_with model: @post, local: true do |form| %>
    <%= render 'layouts/error_messages', model: form.object %>
      <h3>
        投稿内容
      </h3>
      <div class = "form-field">
        <%= form.label :title, "タイトル" %><br />
        <%= form.text_field :title,class:"form-control",id:"title" %>
      </div>
      <div class="form-group">
        <%= form.label :image, "画像" %><br />
        <%= form.file_field :image, autofocus: true, autocomplete: "avatar",class:"file-filed",id:"image" %>
      </div>
      <div class = "form-field">
        <%= form.label :content, "本文" %><br />
        <%= form.text_area :content,class:"form-control",id:"content" %>
      </div>
        <%= form.submit "投稿する", class:"post-new-btn" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class = "all-body">
  <%= link_to  "/users/#{@post.user_id}", method: :get, class:"contributor" do %>
    <div class = "show-avatar">
      <%= image_tag @post.user.avatar_url, class:"post-avatar" %>
      <span class = "contributor-nickname"><%= @post.user.nickname %></span>
    </div>
  <% end %>
  <div class = "details ">
    <div class = "contents">
      <div class = "main-title">
        <%= @post.title%>
      </div>
      <div class = "create-time">
        <%= @post.created_at.to_s(:datetime_jp) %>
      </div>
      <%= image_tag @post.image_url, class:"main-image" %>
      <div class = "main-content">
        <%= @post.content%>
      </div>
      <% if user_signed_in? && current_user.id == @post.user_id %>
        <%= link_to "投稿を編集",edit_post_path(@post.id),class:"post-edit" %>
        <%= link_to "投稿を削除",post_path(@post.id), method: :delete,class:"post-delete" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if user_signed_in? %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),html: { method: :delete },remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-danger" %>
<% end %>

app/views/users/edit.html.erb
<div class = "all-body">
  <div class = main>
    <h2>編集</h2>
    <%= form_for(current_user) do |f| %>
      <div class="form-group">
        <%= f.label :nickname, "ニックネーム",class:"label-name" %><br />
        <%= f.text_field :nickname, autofocus: true, class:"form-control",autocomplete: "nickname" %>
      </div>

      <div class="form-group">
        <%= f.label :email, "メールアドレス" %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control",autocomplete: "email" %>
      </div>

      <div class="form-group">
        <%= f.label :avatar, "アバター画像" %><br />
        <%= f.file_field :avatar, autofocus: true, autocomplete: "avatar",class:"file-filed" %>
      </div>
        <%= f.submit "編集する", class:"new-registration-btn" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class = "show-all">
  <div class = "show-main">
    <div class = "show-main__left">
      <div class = show-main__left__avatar">
        <%= image_tag(@user.avatar_url, class: "show-main__left__avatar__image") %>
      </div>
      <div class = "show-main__left__nickname" >
        <%= @user.nickname %>
      </div>
      <% if user_signed_in? && current_user.id  %>
        <%= link_to  "編集", edit_user_path(current_user), class:"user-edit-btn" %>
      <% end %>
    </div>

    <div class = "show-main__right">
      <% @user ||= current_user %>
      <div class="stats">
        <%= link_to following_user_path(@user), class:"following-link" do %>
          <span class = "following-count"><%= @user.following.count %> 
          フォロー
          </span>
        <% end %>
        <%= link_to followers_user_path(@user), class:"followers-link" do %>
          <span class = "followers-count"><%= @user.followers.count %>
          フォロワー
          </span>
        <% end %>
      </div>
      
      <div class = "follow-btn">
        <%= render 'follow_form' if user_signed_in? && @user.id != current_user.id %>
      </div>
      
    </div>
  </div>

  <div class = "container">
    <% @user.posts.each do |post| %>
      <div class = "col-md-4 main-content">
        <div class = "post-title">
          <%= post.title%>
        </div>
        <div class="content-image">
          <%= image_tag post.image_url,class:"index-image" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class = "show-all">
  <div class = "show-main">
    <div class = "show-main__left">
      <div class = show-main__left__avatar">
        <%= image_tag(@user.avatar_url, class: "show-main__left__avatar__image") %>
      </div>
      <div class = "show-main__left__nickname" >
        <%= @user.nickname %>
      </div>
    </div>

    <div class = "show-main__right">
      <% @user ||= current_user %>
      <div class="stats">
        <%= link_to following_user_path(@user), class:"following-link" do %>
          <span class = "following-count"><%= @user.following.count %> 
          フォロー
          </span>
        <% end %>
        <%= link_to followers_user_path(@user), class:"followers-link" do %>
          <span class = "followers-count"><%= @user.followers.count %>
          フォロワー
          </span>
        <% end %>
      </div>
      <div class = "follow-btn">
        <%= render 'follow_form' if user_signed_in? && @user.id != current_user.id %>
      </div>
    </div>
  </div>

  <div class = "lists">
    <h2 class = "followers-list">フォローリスト</h2>
    <% @user.following.each do |user| %>
      <%= link_to "/users/#{user.id}" ,class:"follower-link" do %>
        <div class = "user-follower col-md-1">
          <%= image_tag user.avatar.url, class:"follower-image" %> 
          <p class ="follower-nickname"><%= user.nickname %></p> 
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show_followers.html.erb
<div class = "show-all">
  <div class = "show-main">
    <div class = "show-main__left">
      <div class = show-main__left__avatar">
        <%= image_tag(@user.avatar_url, class: "show-main__left__avatar__image") %>
      </div>
      <div class = "show-main__left__nickname" >
        <%= @user.nickname %>
      </div>
    </div>

    <div class = "show-main__right">
      <% @user ||= current_user %>
      <div class="stats">
        <%= link_to following_user_path(@user), class:"following-link" do %>
          <span class = "following-count"><%= @user.following.count %> 
          フォロー
          </span>
        <% end %>
        <%= link_to followers_user_path(@user), class:"followers-link" do %>
          <span class = "followers-count"><%= @user.followers.count %>
          フォロワー
          </span>
        <% end %>
      </div>
      <div class = "follow-btn">
        <%= render 'follow_form' if user_signed_in? && @user.id != current_user.id %>
      </div>
    </div>
  </div>

  <div class = "lists">
    <h2 class = "followers-list">フォロワーリスト</h2>
    <% @user.followers.each do |user| %>
      <%= link_to "/users/#{user.id}" ,class:"follower-link" do %>
        <div class = "user-follower col-md-1">
          <%= image_tag user.avatar.url, class:"follower-image" %> 
          <p class ="follower-nickname"><%= user.nickname %></p> 
        </div>
      <% end %>
    <% end %>
  </div>
</div>